[map]
"+test" = "https://www.notion.so/Getting-Started-a6dda56058414bbb8d66a56725c5a82a"
# add more tasks
# define a resolution strategy for each mapping
# define whether it's a one-way sync
# +maria
# +today
