name: CI
on:
  push:
  pull_request:
jobs:
  install_with_pip3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install with pip3 - no extras
        run: |
          pip3 install .
          pip3 show item_synchronizer
      - name: Install with pip3 - all extras
        run: |
          pip3 install .[gcal,notion]
          pip3 show item_synchronizer
      - name: Install with pip3 - gcal
        run: |
          pip3 install .[gcal]
          pip3 show item_synchronizer
      - name: Install with pip3 - notion
        run: |
          pip3 install .[notion]
          pip3 show item_synchronizer
  unittests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.3
      - name: Install prerequisites
        run: |
          poetry install -E gcal -E notion
          sudo ./scripts/install-taskwarrior.sh
          task --version
      - name: Run tests
        run: poetry run pytest --doctest-modules
  style_and_linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.3
      - name: Install prerequisites
        run: poetry install -E gcal -E notion
      - name: Run style checkers and linters
        run: poetry run pre-commit run --all-files
  publish_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish package to pypi
        uses: JRubics/poetry-publish@v1.9
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        with:
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
